[package]
name = "setup-settings"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.16.5"
solana-client = "1.16.5"
solana-program = "1.16.5"
multisend = {path = "../program"}
borsh = "0.10.3"

